### ISSUE TITLE
k8s scan tries to list all namespaces despite namespace filter

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnquery#1022]
**Describe the bug**
a user reported that the api was erroring because we try to request all namespaces despite the filter. it appears we aren't passing the filters through to the api call, and are instead filtering listing all namespaces. this causes an issue for users for whom the namespace filter is more of an rbac requirement than a desire
https://github.com/mondoohq/cnquery/blob/main/motor/discovery/k8s/resolver.go#L108

**Comment by imilchev** [comment]
Not completely fixed. It requires a follow-up that we will tackle shortly
