### ISSUE TITLE
progress bar is off when there are unscored assets

### ISSUE THREAD

**Issue by preslavgerchev** [mondoohq/cnquery#1044]
When scanning a bunch of assets and there are some unscored ones, it throws off the progress bar that tracks all assets

![image](https://user-images.githubusercontent.com/11717082/223749437-98315dfc-ed7a-4f6b-b5da-f46417e5e837.png)

Note the overall bar stays at 56%.

**To Reproduce**
Scan a default (nothing else on it) minikube cluster with only `Kubernetes Best Practices by Mondoo v1.0.0` policy enabled

`~/go/bin/cnspec scan k8s`

While I used cnpec to scan, this is probably a cnquery progress bar issue

**Comment by preslavgerchev** [comment]
@czunker just want to double check this can be closed before i do so, i know you rolled out a fix for it

**Comment by czunker** [comment]
Oh, yes. This was fixed by https://github.com/mondoohq/cnspec/pull/424. Thanks for following up.
