### ISSUE TITLE
Unify the way `_socketsMap` is populated

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#1434]
**What is not working as you expected it?**
We currently have two different ways, to fill the `_socketsMap`:

https://github.com/mondoohq/cnquery/blob/05e6754a2c260d1c35050f51e38fef1be45a1cc1/_resources/packs/core/processes.go#L214

and

https://github.com/mondoohq/cnquery/blob/05e6754a2c260d1c35050f51e38fef1be45a1cc1/_resources/packs/core/port.go#L285

The implementation in port was introduced with https://github.com/mondoohq/cnquery/pull/531.

The current assumption is, we could use the way it is done in `port.go` also in `processes.go` to only have one way of getting the information.

**Where on the platform does it happen?**
`cnquery`

**Comment by czunker** [comment]
This should be done after the plugin refactoring is done.

**Comment by arlimus** [comment]
Apart from the proposed improvements in #1928, I double-checked it against main on 6e2a9514 and noticed (1) we only have one way of handling the internal ports list now (via `processes2ports` on `mqlPorts`) and (2) it is only modified by `processesBySocket` now
