### ISSUE TITLE
asset resource works only for os

### ISSUE THREAD

**Issue by imilchev** [mondoohq/cnquery#1486]
The `asset` resource seems to be working only for OS. Every other provider plugin that creates an asset results in an error because they all get redirected to the OS provider. For example, `cnspec run host https://mondoo.com -c 'asset'`:
```
→ loaded configuration from /Users/ivanmilchev/.config/mondoo/mondoo.yml using source default
! using builtin provider for os
cannot find connection type host
asset: no data available
```

The error is originating from https://github.com/mondoohq/cnquery/blob/main/providers/os/provider/provider.go#L181

**Comment by vjeffrey** [comment]
note: if you do not have the os provider installed, it works. if you do, then it randomly fails.

**Comment by arlimus** [comment]
This is likely due to the fact that the os resource defines some part of asset. Having a look into it...

**Comment by preslavgerchev** [comment]
https://github.com/mondoohq/cnquery/issues/1534 has some details on this too
