### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS does not work

### ISSUE THREAD

**Issue by jaym** [mondoohq/cnquery#1514]
We are unable to use GOOGLE_APPLICATION_DEFAULTS when trying to scan a GCP org. The issue seems to be that during discovery, the google provider gets created with credentials that are not resolved. Similarly, we need to be able to pass these credentials in the inventory.yaml, and the issue of that not working is probably the same.

Using the following change, I am able to get it to work but I don't understand exactly what is going on here (why are the credentials not resolved for discovery):

```
diff --git a/motor/discovery/gcp/resolver_org.go b/motor/discovery/gcp/resolver_org.go
index 4d9f8276..a6b6078b 100644
--- a/motor/discovery/gcp/resolver_org.go
+++ b/motor/discovery/gcp/resolver_org.go
@@ -29,6 +29,21 @@ func (r *GcpOrgResolver) Resolve(ctx context.Context, tc *providers.Config, cred
                return resolved, nil
        }

+       tc = tc.Clone()
+       resolvedCredentials := []*vault.Credential{}
+       for i := range tc.Credentials {
+               credential := tc.Credentials[i]
+               if credential.SecretId != "" && credsResolver != nil {
+                       resolvedCredential, err := credsResolver.GetCredential(credential)
+                       if err != nil {
+                               return nil, err
+                       }
+                       credential = resolvedCredential
+               }
+               resolvedCredentials = append(resolvedCredentials, credential)
+       }
+       tc.Credentials = resolvedCredentials
+
        provider, err := gcp_provider.New(tc)
        if err != nil {
                return nil, err
```

**Comment by tas50** [comment]
@jaym following up from standup this morning: can you make sure to test if these credentials work with a project scan?

**Comment by chris-rock** [comment]
Credentials are parsed in here https://github.com/mondoohq/cnquery/blob/v8/apps/cnquery/cmd/builder/parse.go#L454-L491. We need to use `m, err := resolver.NewMotorConnection(ctx, tc, credsResolver)` similar to https://github.com/mondoohq/cnquery/blob/v8/motor/discovery/azure/resolver.go#L54-L59. If you use the provider directly the resolution needs to be done manual.
