### ISSUE TITLE
ssh provider is missing --identity-file flag

### ISSUE THREAD

**Issue by imilchev** [mondoohq/cnquery#1525]
The ssh provider is missing the `--identity-file` flag. Not sure if that's intentional or not but now I don't know how to specify a key to be used

**Comment by czunker** [comment]
This was fixed with https://github.com/mondoohq/cnquery/pull/1609/files#diff-e8c37eed9d039faad8764d2183b4f33043a5b56ae76f3a8768f3f4aa72f2e223
