### ISSUE TITLE
v9 generated schema includes to much fields

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#1529]
**Describe the bug**
When running `cnquery run terraform .../edge/main.tf -c "terraform{ * }"` I see some "not found" errors:
```
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
7 errors occured:
        * cannot find 'module' in resource 'terraform'
        * cannot find 'block' in resource 'terraform'
        * cannot find 'state' in resource 'terraform'
        * cannot find 'settings' in resource 'terraform'
        * cannot find 'plan' in resource 'terraform'
        * cannot find 'fileposition' in resource 'terraform'
        * cannot find 'file' in resource 'terraform'
```

According to the lr files, these fields do not belong to the `terraform` resource:
```
// Terraform Configuration Files
terraform {
  // Access to individual files including .tf and .tf.json files
  files() []terraform.file
  // The attributes defined in .tfvars and .tfvars.json
  tfvars() dict
  // List all referenced terraform modules
  modules() []terraform.module
  // Raw HCL blocks
  blocks() []terraform.block
  // Provider blocks
  providers() []terraform.block
  // Data sources blocks
  datasources() []terraform.block
  // All blocks with type resource
  resources() []terraform.block
  // Variable blocks
  variables() []terraform.block
  // Output blocks
  outputs() []terraform.block
}
```

The generated go struct looks fine:
```
type mqlTerraform struct {
	MqlRuntime *plugin.Runtime
	__id string
	// optional: if you define mqlTerraformInternal it will be used here
	Files plugin.TValue[[]interface{}]
	Tfvars plugin.TValue[interface{}]
	Modules plugin.TValue[[]interface{}]
	Blocks plugin.TValue[[]interface{}]
	Providers plugin.TValue[[]interface{}]
	Datasources plugin.TValue[[]interface{}]
	Resources plugin.TValue[[]interface{}]
	Variables plugin.TValue[[]interface{}]
	Outputs plugin.TValue[[]interface{}]
}
```

But the generated schema includes more fields (16 in total vs. 9 in lr):
![image](https://github.com/mondoohq/cnquery/assets/827818/d74bcaaa-58f1-4273-9866-69a14507cba4)

It looks to me like other resources, which start with `terraform.` are included as fields, e.g., `terraform.plan`.

Double checked this with the k8s resource. There it also happens. The generated schema includes 54 fields, but the lr definition only has 23.

**To Reproduce**

1. Running something like the above command against terraform or k8s
2. Note the error

**Expected behavior**
Only fields defined in lr should be included in the schema.

**Comment by vjeffrey** [comment]
could this be an issue with marking resources as private vs not in the lr files?

**Comment by arlimus** [comment]
+1 I think it was private resources

No longer an issue on latest main:

![image](https://github.com/mondoohq/cnquery/assets/1307529/2199cab9-528a-4b95-88ef-5e5f48bb5420)
