### ISSUE TITLE
Aliases in v9 aren't working

### ISSUE THREAD

**Issue by imilchev** [mondoohq/cnquery#1608]
While working on #1590 I noticed that aliases aren't. I'm not sure if it's all aliases or just some but in that case we have https://github.com/mondoohq/cnquery/blob/main/providers/gcp/resources/gcp.lr#L10 If I type `gcp.compute.network` I get an error: 
```
cannot find resource gcp.compute in this provider
gcp.compute.network: no data available
```

Using the actual resource seems to be working correctly: `gcp.project.computeService.network`

We should fix this before releasing v9 since policies depend on these aliases

**Comment by arlimus** [comment]
This should be fixed, I just ran a tiny test:

![image](https://github.com/mondoohq/cnquery/assets/1307529/adcb8769-4e46-4666-bda6-5787e98d4b40)

![image](https://github.com/mondoohq/cnquery/assets/1307529/90743a4c-2ae5-4fc5-bd16-e74ed4835483)

Please reopen and pin to the v9 board in case I missed something
