### ISSUE TITLE
Running query packs against assets doesn't work in v9

### ISSUE THREAD

**Issue by preslavgerchev** [mondoohq/cnquery#1636]
**Describe the bug**
No query pack can currently run against any asset in v9 due to how we to discovery/connection at present.

1. We do an initial `Connect` to the provider that returns a rather empty asset with only type/config opts being filled in.
2. Here (https://github.com/mondoohq/cnquery/blob/main/explorer/scan/local_scanner.go#L185) we fill in the connected asset.
3. We pull in packs and attempt to run the asset filter queries, such as `asset.kind == api`. This goes through several layers but eventually ends up here: https://github.com/mondoohq/cnquery/blob/main/providers/runtime.go#L419
4. Any asset filter query is attempted to be evaluated against this asset

There are several problems here.
- The inventory, discovered in https://github.com/mondoohq/cnquery/blob/main/explorer/scan/local_scanner.go#L185 is not used. This is a quick fix to get the right assets in, but does not solve everything.
- The runtime will always try to create the asset, using `Provider.Connection.Asset`, which at that time is the 'empty' root asset
This leads to panics in the core provider as most of those assets do not have a platform, so accessing `asset.Platform` in https://github.com/mondoohq/cnquery/blob/main/providers/core/provider/provider.go#L48 panics
- Even if we fix the panics by guarding the asset.Platform fields, the asset filter MQL queries will never match. We're evaluating against an empty root asset where the platform is usually empty. Instead this should be done against the discovered asset in the inventory, to which we're trying to connect.

**Comment by arlimus** [comment]
This is working again thanks to your help + others!! Thank you!

I'm closing this in favor of having more fine-grained issues for specific pieces of functionality that are still failing

![image](https://github.com/mondoohq/cnquery/assets/1307529/93dce66e-08cd-4c5d-aaec-407e788f09e8)
