### ISSUE TITLE
Decide how to implement provider shutdown

### ISSUE THREAD

**Issue by imilchev** [mondoohq/cnquery#1664]
See https://github.com/mondoohq/cnquery/pull/1663 for more details

**Comment by chris-rock** [comment]
may be solved with https://github.com/mondoohq/cnquery/pull/1753

**Comment by arlimus** [comment]
We have an initial version of provider shutdown implemented now:

1. Every provider implements `rpc Shutdown(ShutdownReq) returns (ShutdownRes);`
2. We have a `func (p *RunningProvider) Shutdown() error` implementation that calls all providers
3. And we have a `coordinator.Shutdown` to wrap things up. 

I think there is more to come to clean up the provider shutdown and more efficiently shut things down during use in a follow-up
