### ISSUE TITLE
cloud detect failing for ec2

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnquery#1813]
```
DBG run command command="curl http://169.254.169.254/latest/dynamic/instance-identity/document" provider=ssh
DBG failed to get AWS platform id error="failed to decode EC2 instance identity document: invalid character '<' looking for beginning of value" platform=["linux","unix","os"]
```

**Comment by vjeffrey** [comment]
looks like we now need to fetch from 
`const identityUrl = "TOKEN=`curl -X PUT \"http://169.254.169.254/latest/api/token\" -H \"X-aws-ec2-metadata-token-ttl-seconds: 21600\"` && curl -H \"X-aws-ec2-metadata-token: $TOKEN\" -v http://169.254.169.254/latest/dynamic/instance-identity/document"`

**Comment by tas50** [comment]
IMDSv2 is required by our policies so we need to snag tokens now
