### ISSUE TITLE
EKS (add readOnlyPort to k8s.kubelet.configuration)  & AKS issues

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnquery#1831]
Issue 1:  EKS in amazon
```
Hi guys, we noticed that in EKS 
readOnlyPort
 does exist in the  kubelet-config.json file of the worker node and it should appear in the outcome of the 
k8s.kubelet.configuration
 command. But it is not the case.  We need this value. Our assumption is that all content of the kubelet-config.json file is being read beside other things. 
```

// Kubernetes Kubelet configuration
private k8s.kubelet {
  // Kubelet config file
  configFile core.file
  // Kubelet process
  process core.process
  // Combination of config file parameters and cli parameters
  configuration dict
}
```
    // readOnlyPort is the read-only port for the Kubelet to serve on with
    // no authentication/authorization.
    // The port number must be between 1 and 65535, inclusive.
    // Setting this field to 0 disables the read-only service.
    // Default: 0 (disabled)
    // +optional
    ReadOnlyPort int32 `json:"readOnlyPort,omitempty"`
````

its probably not beign read into the struct if its missing, and then we're not explicitly setting it to 0?

***************************

Issue 2:   AKS in Azure

I post another probably similar problem in AKS here, might be useful to have it.

It is related to "Ensure that the --client-ca-file argument is set as appropriate"  Test in AKS
![Screenshot_from_2023-09-22_12-50-34](https://github.com/mondoohq/cnquery/assets/56231339/ef467aa4-6d1a-418e-ace8-3f8682cfd375)

It should not show empty (null)!

**Comment by czunker** [comment]
@HRouhani FYI

**Comment by HRouhani** [comment]
Thanks @czunker cool job
