### ISSUE TITLE
cnspec failing to download os provider

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#1833]
**Describe the bug**

On my Raspbian box I'm getting the following error when running the latest beta:

```
pi@adsbexchange:~ $ sudo ./cnspec scan
! can't find any paths for providers, none are configured system-path=/opt/mondoo/providers
x failed to install os-9.0.0: failed to create
```

The /opt/mondoo dir is not created:

```
pi@adsbexchange:~ $ ls -lah /opt/
total 8.0K
drwxr-xr-x  2 root root 4.0K Apr  4  2022 .
drwxr-xr-x 19 root root 4.0K Jul 21 23:17 ..
```

**Comment by vjeffrey** [comment]
i think its this bit of code:
```
func InstallIO(reader io.ReadCloser, conf InstallConf) ([]*Provider, error) {
    if conf.Dst == "" {
        conf.Dst = HomePath
    }

    if !config.ProbeDir(conf.Dst) {
        log.Debug().Str("path", conf.Dst).Msg("creating providers directory")
        if err := os.MkdirAll(conf.Dst, 0o755); err != nil {
            return nil, errors.New("failed to create " + conf.Dst)
        }
```
the thing that calls it fills in the rest of the err
i think it's getting here:
```
    if conf.Dst == "" {
        conf.Dst = HomePath
    }
```
and setting conf.Dst to your home path
but we never detected a home path for your system
so then it fails.

**Comment by arlimus** [comment]
I was able to initially replicate this bug, but after some fixes and updating cnspec it seems to have gone away. Added a bump in dependencies for cnspec. Please try again once these merge.
