### ISSUE TITLE
aws ebs scan needs to clean up after the scan is done

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#1847]
**Describe the bug**
The aws ebs scan does not clean up after the scan is done.
The VM running the scan still has mounts:
```
/dev/xvdr1 on /tmp/cnspec-scan2653270300 type xfs (rw,relatime,seclabel,nouuid,attr2,inode64,logbufs=8,logbsize=32k,sunit=1024,swidth=1024,noquota)
/dev/xvdw1 on /tmp/cnspec-scan246994269 type xfs (rw,relatime,seclabel,nouuid,attr2,inode64,logbufs=8,logbsize=32k,sunit=1024,swidth=1024,noquota)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=97216k,nr_inodes=24304,mode=700,uid=1000,gid=1000)
/dev/xvde1 on /tmp/cnspec-scan3228638179 type xfs (rw,relatime,seclabel,nouuid,attr2,inode64,logbufs=8,logbsize=32k,sunit=1024,swidth=1024,noquota)
```

And the volumes are still present:
![image](https://github.com/mondoohq/cnquery/assets/827818/2f4f55cb-1f5b-415a-901c-c14f1487b81a)

**To Reproduce**

1. Run an was ebs scan
2. Check mounts on the VM or volumes in the AWS console
3. Note the error

**Expected behavior**
The scan should clean up after it is finished successfully.

**Comment by vjeffrey** [comment]
i have this partially working in my tests, we seem to be wiping away all the info i need by the time i get to shutdown so im trying to reassemble all that info
