### ISSUE TITLE
v9 mql evaluation behaviour change for sshd.config.ciphers == null

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnquery#1874]
**Describe the bug**

The evaluation of `sshd.config.ciphers == null` has changed in v9 compared to v9. In general I find the behavior in v9 more correct, but I'd like to ensure we have consensus about the behavior.

v8:

```
cnquery> sshd.config.ciphers
sshd.config.ciphers: []
cnquery> sshd.config.ciphers == null
[ok] value: []
cnquery> sshd.config.ciphers != null
[failed] sshd.config.ciphers != null
  expected: != _
  actual:   []
```

v9:

```
cnquery> sshd.config.ciphers
sshd.config.ciphers: []
cnquery> sshd.config.ciphers == null
[failed] sshd.config.ciphers == null
  expected: == _
  actual:   []
cnquery> sshd.config.ciphers != null
[ok] value: []
```

**To Reproduce**

run cnquery / cnspec with an sshd config where no ciphers are defined.

**Expected behavior**

tbd.

**Desktop (please complete the following information):**

cnquery v9.0.0-beta3 (d3f44c0e3, unknown)

**Comment by arlimus** [comment]
Great catch, thanks for bringing it up!

v9 definitely is more consistent with the behavior we want.

Additionally, we'll introduce `empty` to better handle this concept in the future.

Closing this for now, referencing: https://github.com/mondoohq/cnquery/pull/1884
