### ISSUE TITLE
v9: dns.fqdn is displaying IP address

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#1958]
**Describe the bug**
On a system with no FQDN, v9 is listing the fqdn as the IP, while V8 has no data.

```
pi@adsbexchange:~ $ hostname -f
localhost
```

v9:

```
cnquery> dns
dns: dns fqdn="172.16.1.249"
```

v8:

```
cnquery> dns
dns: dns fqdn=""
```

**Comment by mariuskimmina** [comment]
Can't reproduce on my maschine 

```
uname -a
Linux pop-os 6.2.6-76060206-generic #202303130630~1689015125~22.04~ab2190e SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux
```

```
hostname -f
pop-os.localdomain
```

```
cnquery> dns.fqdn
! using builtin provider for network
dns.fqdn: ""
cnquery> dns
dns: dns fqdn=""
```

Build from tag v9.0.0-beta9

Is it a distro specific issue or has it already been fixed? Does the issue still occur for you?
I have additionally also tested it on Ubuntu but couldn't reproduce it there either.

**Comment by chris-rock** [comment]
I am also not able to reproduce this on macos, @tas50 can you share more information about this issue?

**Comment by tas50** [comment]
Still happening on my raspbian box over ssh

**Comment by czunker** [comment]
I can reproduce this with a debian 11 Vagrantbox and cnquery v9-beta15:
```
[vagrant@localhost ~]$ hostname
localhost.localdomain
```

```
cnquery-9b15 run vagrant default -c "dns" 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
dns: dns fqdn="127.0.0.1"
```
