### ISSUE TITLE
scan speed depends on the amount of installed providers

### ISSUE THREAD

**Issue by imilchev** [mondoohq/cnquery#2084]
Running a `cnquery scan k8s` for minikube with all providers locally installed is really slow. It takes about 30seconds per discovered asset. If I delete all providers and leave just `k8s` and `network` it takes 2secs per asset

**Comment by scottford-io** [comment]
@imilchev I am running into this all over the place. Scans are taking significantly longer with v9 than they did with v8. Even local scans of files such as Terraform which used to take milliseconds now take up to 30 seconds.

**Comment by vjeffrey** [comment]
this was resolved, or at least made much better with https://github.com/mondoohq/cnquery/pull/2196

**Comment by vjeffrey** [comment]
related to https://github.com/mondoohq/cnspec/issues/833
