### ISSUE TITLE
V9 MQL docs generation changes

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#2088]
**Describe the bug**
This is a single box describing various differences discovered during the generation of MQL docs for v9.

---
![image](https://github.com/mondoohq/cnquery/assets/1015200/0fb8e7d7-66b6-43e4-872f-d52b3f011506)

- [x] Issue
- [ ] Expected

---

![image](https://github.com/mondoohq/cnquery/assets/1015200/38123553-b670-4242-83a7-74c622f16ab0)

![image](https://github.com/mondoohq/cnquery/assets/1015200/ea9e8f3b-7bf0-4702-97da-623681a029a5)

- [x] Issue
- [x] Expected

---

![image](https://github.com/mondoohq/cnquery/assets/1015200/ecd61d2d-d78c-4f16-a081-a64a1926578d)

- [x] Issue
- [ ] Expected

---

![image](https://github.com/mondoohq/cnquery/assets/1015200/ca32fa5a-6b84-4d4e-855a-feb74b5c911b)

- [ ] Issue
- [x] Expected

---

OS snippets are missing even though they're in the lr.manifest.yaml file

![image](https://github.com/mondoohq/cnquery/assets/1015200/0fb18dda-7ce0-4269-ab94-ba91035552ab)

- [x] Issue
- [ ] Expected

---

![image](https://github.com/mondoohq/cnquery/assets/1015200/d25dffb7-c5ad-4c6b-9a38-3683c569eaa7)

- [ ] Issue
- [x] Expected

---

![image](https://github.com/mondoohq/cnquery/assets/1015200/5bf1ad6d-96b8-4f36-b9a3-72d54910e408)

- [ ] Issue
- [x] Expected

---

Kublet moves from K8s to OS?
![image](https://github.com/mondoohq/cnquery/assets/1015200/bac2cc34-77c7-4e00-8074-9dc20b5be336)

- [x] Issue
- [ ] Expected

---
This is defined in the LR file, but isn't showing up

![image](https://github.com/mondoohq/cnquery/assets/1015200/004f7674-cb88-4998-914f-875bc52f985b)

- [x] Issue
- [ ] Expected

**Comment by arlimus** [comment]
Follow-ups:
1. Move `kubelet` from `os` to `k8s` and figure out where it is positioned in relation to `k8s.kubelet`. I'm going to assume we want to call out from the k8s provider to the os provider here, but we need to further analyze this use-case.
2. The examples thingy with yum.repo is missing, it exists in the manifest but doesn't render out. Needs to be tracked down, low priority.
3. The supported platform thing also looks like a bug, unclear on why it shows up and also of lower priority
