### ISSUE TITLE
cnquery shell (without `local`) doesn't work in v9

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnquery#2103]
```
benr@swell:~/Downloads$ cnquery shell
benr@swell:~/Downloads$ echo $?
0
benr@swell:~/Downloads$ cnquery shell local
→ found a new version for 'os' provider installed=9.0.8 latest=9.0.10
→ successfully installed os provider path=/home/benr/.config/mondoo/providers/os version=9.0.10
→ loaded configuration from /home/benr/.config/mondoo/mondoo-cuddletech.yml using source $MONDOO_CONFIG_PATH
→ connected to Ubuntu 22.04.2 LTS
  ___ _ __   __ _ _   _  ___ _ __ _   _ 
 / __| '_ \ / _` | | | |/ _ \ '__| | | |
| (__| | | | (_| | |_| |  __/ |  | |_| |
 \___|_| |_|\__, |\__,_|\___|_|   \__, |
  mondoo™      |_|                |___/  interactive shell

cnquery> 
```

**Comment by mariuskimmina** [comment]
I observed that when at first `./cnquery shell` was indeed doing nothing, after `./cnquery shell local` went through once, the default shell command also started to work. I assume that running `./cnquery shell local` did some provider setup that was not happening when just running `./cnquery shell` still looking for a proper fix

**Comment by mariuskimmina** [comment]
If I simply have no os provider installed at all, the command also works fine without the `local` argument

**Comment by mariuskimmina** [comment]
It seems that on this line

```
	if p, ok := existing[providers.DefaultOsID]; ok {
```

v9 is looking for `go.mondoo.com/cnquery/v9/providers/os` but the os provider version 9.0.7 is still registered as `go.mondoo.com/cnquery/providers/os` - which is causes no default provider to be set 

So this seems to be fixed by simply updating to the newer provider version, I am thinking if there is a good way to make add an auto update here

**Comment by mariuskimmina** [comment]
Talked with @chris-rock, we want to stick with the exact provider id here and accept that people who were using the beta provider versions need to upgrade manually once - do you agree @vjeffrey

**Comment by mariuskimmina** [comment]
We can also temporarily allow the old id as well to make the upgrade smoother for beta users, see the PR above
