### ISSUE TITLE
ebs scan failing with describe instances missing region error 

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnquery#2158]
```
FTL could not load asset information error="rpc error: code = Unknown desc = unable to validate: operation error EC2: DescribeInstances, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region"
```

this is new, when i last tested a couple weeks ago things worked.

i'm also super unclear on how we're getting here...none of the logging i would expect is showing up
```
→ using service account credentials
→ discover related assets for 1 asset(s)
x unable to connect to asset error="rpc error: code = Unknown desc = unable to validate: operation error EC2: DescribeInstances, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region"
```

ssm and instanceconnect on the cli are also misbehaving. these all worked before, im not sure what's going on yet

**Comment by czunker** [comment]
> But, now the ebs scanning is not cleaning up after the scan:

This looks more like a general issue. It also affects gcp snapshot scanning. With ephemeral runtimes, the shutdown behavior changed:
https://github.com/mondoohq/cnquery/pull/2050/files#diff-7263c3839c73627bf39872d6eafc82a803d9b052ece899a5a14fb5cf8497d844R64-R66

**Comment by czunker** [comment]
Switching to an `EphemeralRuntime` fixes the cleanup for the run command:
```
DBG close aws ebs connection
DBG unmount volume dir=/tmp/cnspec-scan2920273538
→ detach volume
→ waiting for volume detachment completion state=in-use
→ waiting for volume detachment completion state=available
DBG remove created dir dir=/tmp/cnspec-scan2920273538
→ delete created volume
→ deleted temporary volume created by Mondoo vol-id=vol-06169f7dadc776b4b
```

**Comment by czunker** [comment]
Got the detach error again:
```
DBG mount volume to scan dir device=/dev/xvdp1 fstype=xfs opts=nouuid scandir=/tmp/cnspec-scan1047086078
x failed to mount dir error="file exists" attached-fs=/dev/xvdp1 fs-type=xfs opts=nouuid scan-dir=/tmp/cnspec-scan1047086078
x unable to complete mount step error="file exists"
DBG close aws ebs connection
DBG unmount volume dir=
x failed to unmount dir error="no such file or directory"
x failed to unmount dir error="no such file or directory"
x unable to unmount volume error="no such file or directory"
→ detach volume
x unable to detach volume error="operation error EC2: DetachVolume, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region"
DBG remove created dir dir=
→ delete created volume
x unable to delete volume error="operation error EC2: DeleteVolume, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region"
→ deleted temporary volume created by Mondoo vol-id=vol-0febcc58d6815f026
FTL failed to run query error="file exists"
```

**Comment by vjeffrey** [comment]
the describe instances error is a red herring, we're never getting to the correct provider in the code

**Comment by czunker** [comment]
I now also manged to trigger the same error we saw with the gcp snapshot scanning:
```
DBG platform> detected os family=["linux","unix","os"] platform=amazonlinux
DBG starting query execution qrid=aRSd7vfjN/s=
! using builtin provider for os
DBG finished query execution qrid=aRSd7vfjN/s=
DBG VYvXd9DoeA22juTEFywXJb89sXLsOc7eHhrCj6WwJqVtuEUXvgQeEsFXaVhe72J+NBCOk9tV3F4BZ4g67moVHA== finished
DBG graph has received all datapoints
cannot find connection type ebs
os.hostname: no data available
```
I had to change the query to `os.hostname` to actually trigger the os provider.

I'll now give https://github.com/mondoohq/cnquery/pull/2187 and https://github.com/mondoohq/cnquery/pull/2127 a try to figure out which one fixes the issue.

**Comment by czunker** [comment]
Hit another error:
```
DBG graph has received all datapoints
cannot determine hostname
os.hostname: null
```

**Comment by czunker** [comment]
Got it working, including cleanup:
```
sudo ./cnquery run aws ec2 ebs snapshot snap-0ebf40b85d616d284 -c "os.hostname"
→ no Mondoo configuration file provided, using defaults
os.hostname: "ip-172-31-39-211.eu-central-1.compute.internal"
```

**Comment by czunker** [comment]
> I now also manged to trigger the same error we saw with the gcp snapshot scanning:
> 
> ```
> DBG platform> detected os family=["linux","unix","os"] platform=amazonlinux
> DBG starting query execution qrid=aRSd7vfjN/s=
> ! using builtin provider for os
> DBG finished query execution qrid=aRSd7vfjN/s=
> DBG VYvXd9DoeA22juTEFywXJb89sXLsOc7eHhrCj6WwJqVtuEUXvgQeEsFXaVhe72J+NBCOk9tV3F4BZ4g67moVHA== finished
> DBG graph has received all datapoints
> cannot find connection type ebs
> os.hostname: no data available
> ```
> 
> I had to change the query to `os.hostname` to actually trigger the os provider.
> 
> I'll now give #2187 and #2127 a try to figure out which one fixes the issue.

I tried both, but only #2127 works for builtin and plugins. Updated #2187 . Perhaps we can combine both.
