### ISSUE TITLE
Arrays are all duplicates of the first element if id() is not implemented

### ISSUE THREAD

**Issue by mariuskimmina** [mondoohq/cnquery#2170]
I've come across this a couple of times now, whenever a resource has a property that's an array of another resource such as

```
  policies() []atlassian.admin.organization.policy
```

Where `atlassian.admin.organization.policy` is defined as

```
atlassian.admin.organization.policy @defaults("id") {
  // Policy ID
  id string
}
```

And we do **not** implement the following function 

```
func (a *mqlAtlassianAdminOrganizationPolicy) id() (string, error) {
	return a.Id.Data, nil
}
```

But instead rely on the default `_id` implementation then all elements in this array will be copies of the first element. The number of elements in the array still seems to be correct in such a case.

Related: #1873 #1827

**Comment by chris-rock** [comment]
This is by design, not a bug
