### ISSUE TITLE
AWS/GCP snapshot cleanup isn't working with builtin providers

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#2190]
**Describe the bug**
While debugging #2171 with builtin providers, I noticed that cleanup is not happening.

For ebs and gcp snapshot scanning, we call some cleanup after the scan is done. This cleanup  is triggered via the provider shutdown. But builtin providers are added to the running providers, so they aren't shut down later:
https://github.com/mondoohq/cnquery/blob/main/providers/coordinator.go#L107-L117

This makes debugging harder.

**To Reproduce**

1. Run a GCP or EBS snapshot scan with builtin providers for aws/gcp and os.
2. Notice the scan finishing
4. Note that the cloud console still shows created volumes and mountpoints are still present in the VM

**Expected behavior**
We should be able to execute this cleanup also with builtin providers.

**Comment by imilchev** [comment]
this should now work with the new disconnect logic
