### ISSUE TITLE
The resource schema cannot lookup resources by their alias

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#2364]
**Describe the bug**

We will use GCP as an example.

The resource I'd like to lookup is https://github.com/mondoohq/cnquery/blob/main/providers/gcp/resources/gcp.lr#L1174

It has an alias defined: https://github.com/mondoohq/cnquery/blob/main/providers/gcp/resources/gcp.lr#L20

Taking this code:
```
resourceInfo := defaultSchema.Lookup("gcp.project.bigquery")
require.NotNil(t, resourceInfo)
require.Equal(t, "gcp.project.bigquery", resourceInfo.Name)
resourceInfo = defaultSchema.Lookup("gcp.project.bigqueryService")
require.NotNil(t, resourceInfo)
require.Equal(t, "gcp.project.bigqueryService", resourceInfo.Name)
```
The first lookup fails, the second works.

Not sure whether this works as intended or it's a bug.

**Expected behavior**
I can lookup resources by their alias.

**Comment by arlimus** [comment]
From the schema I see:

```alias gcp.bigquery = gcp.project.bigqueryService```

This means both `gcp.bigquery` and `gcp.project.bigqueryService` should work => confirmed

**Comment by arlimus** [comment]
To clarify: `gcp.bigquery` is a resource, `gcp.project.bigqueryService` is a resource. Both can be called via `Lookup`. However `gcp.project.bigquery` is a field in a project, i.e. it cannot be looked up via `Lookup` but must be looked up via the field. Either way, all 3 calls work when things come together.
