### ISSUE TITLE
make sure coordinator is shut down on process panic

### ISSUE THREAD

**Issue by imilchev** [mondoohq/cnquery#2378]

**Comment by czunker** [comment]
Some docs around this: https://go.dev/blog/defer-panic-and-recover

We defer+recover already use this in other code.

**Comment by czunker** [comment]
From what I understood, this can be closed with https://github.com/mondoohq/cnspec/pull/898 as the solution.

**Comment by czunker** [comment]
At different points in the code we close the runtime with the coordinator:
```
		runtime.Close()
		providers.Coordinator.Shutdown()
```
Do we need to include the `runtime.Close()` in the defer?
