### ISSUE TITLE
repo is missing protected branches

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#240]
**Describe the bug**
main branch is not protected.

**To Reproduce**
1. push something to main
2. It will be accepted

**Expected behavior**
Push should be denied.

**Screenshots**
![image](https://user-images.githubusercontent.com/827818/194924770-7e809015-af3a-405e-b9d9-fe50c18b58e8.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by chris-rock** [comment]
This has been fixed a few days ago
