### ISSUE TITLE
:bug: Linux/Unix systemctl status `masked` is not recognized by cnquery

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#2432]
**Describe the bug**
The Linux service status `masked` is not recognized by cnquery:

**To Reproduce**

1. Mask a service
```
systemctl mask avahi-daemon.service
```
2. Check status via systemctl
```
# systemctl status avahi-daemon.service
○ avahi-daemon.service
     Loaded: masked (Reason: Unit avahi-daemon.service is masked.)
     Active: inactive (dead)
```
3. Check status via cnquery
```
cnquery run -c 'service("avahi-daemon.service") {*}'
→ no provider specified, defaulting to local. Use --help to see all providers.
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
service: {
  running: false
  masked: false
  enabled: false
  installed: false
  name: "avahi-daemon.service"
  type: null
  description: null
```

**Expected behavior**
The service status `masked` needs to be displayed correctly.

**Screenshots or CLI Output**
![image](https://github.com/mondoohq/cnquery/assets/112621871/9261e0eb-b5cc-4935-8f0f-69418d1eabcb)

**Additional context**
```
cnquery version
cnquery 9.4.0 (a9102f6d, 2023-10-27T00:17:51Z
```

**Comment by mariuskimmina** [comment]
@mm-weber you should get the correct results if you leave out the `.service` ending

```
cnquery run -c 'service("avahi-daemon") {*}'
```

I am working on a fix so that in the future it will work both with and without the `.service`

**Comment by mick-lue** [comment]
I think one part of the issue might be this [line](https://github.com/mondoohq/cnquery/blob/d2f48999c4e2a84527e1ade08753d8cb0cbfc0dc/providers/os/resources/services/systemd.go#L73C31-L73C72) in the SystemDServiceManager List() function:
`        c, err := s.conn.RunCommand("systemctl --all list-units --type service")`

When I run the command `systemctl --all list-units --type service` on an Ubuntu 22.04 for example, it lists 104 loaded units and I do not see any masked services in that list.
On the other hand, `systemctl --all list-unit-files --type service` on the same systems show 139 unit files and marks some as masked
That might be why `cnquery --config /etc/mondoo/mondoo.yml run -c 'service("rsync") { * }'` returns a service that was [only initialised](https://github.com/mondoohq/cnquery/blob/35d2ff3e2cd9c61091964b108e6036d124f69a7a/providers/os/resources/services.go#L18C11-L18C11):
```
service: {
  enabled: false
  running: false
  type: null
  description: null
  name: "rsync"
  masked: false
  installed: false
}
```
(related to https://github.com/mondoo-community/workspace-ivi/issues/11)

**Comment by mariuskimmina** [comment]
I do get at least one masked service from `systemctl --all list-units --type service` but you are still right that `systemctl --all list-unit-files --type service` returns more. 

```
systemctl --all list-units --type service | grep masked
● ubuntu-recovery-tasks.service                         masked    inactive dead    ubuntu-recovery-tasks.service
```

I am on ubuntu 22.04 as well
