### ISSUE TITLE
os provider not updating

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnquery#2461]
i have cnspec 9.5.1 (e8298bf, 2023-11-02T10:07:22Z) running on my windows server 2016. The service is not running because the os provider is not update to date.

<img width="683" alt="Screenshot 2023-11-03 at 13 47 57" src="https://github.com/mondoohq/cnquery/assets/7220740/9eee62b1-1cae-47a4-9c3a-dcd9d10c0ede">

**Comment by chris-rock** [comment]
This problem is not restricted to Windows. The serve-mode itself does not update the providers. We should schedule run a provider update call one a day in the background.
