### ISSUE TITLE
`cnquery run` and certificates for authentication does not work

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#2572]
**Describe the bug**
```
cnquery run ms365 --client-id XXX --certificate-path /home/christian/tmpblswgv28.pem --tenant-id XXX -c "ms365.teams" 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
FTL failed to run query error="rpc error: code = Unknown desc = cannot fetch credentials for microsoft provider: could not parse provided certificate at /home/christian/tmpblswgv28.pem: pkcs12: error reading P12 data: asn1: syntax error: sequence truncated"
```

Debugging this a bit further, the certificate data provided to the azidentity dep is empty:
![Screenshot from 2023-11-15 09-38-35](https://github.com/mondoohq/cnquery/assets/827818/f7abedad-ca53-4c10-9669-94d5a4b8a9f8)
(You can ignore the file suffix. I tried different formats.)

**To Reproduce**

1. Create auth data for ms365: https://mondoo.com/docs/platform/infra/saas/ms365/
2. Run above query
3. Note the error

**Expected behavior**
I'd expect to be authenticated.

**Desktop (please complete the following information):**

- cnquery 9.7.0

**Additional context**
The same with `cnquery shell` works.

**Comment by mm-weber** [comment]
I can confirm this is still an issue with `cnquery run` in `cnquery v10.1.4 (74ea320c3, unknown)`

```
cnquery run ms365 -c "microsoft.security.latestSecureScores.controlScores.where(controlName == 'SigninRiskPolicy').all(_['score'] == 7)" --certificate-path ~/Downloads/mondoo-ms365-Dec8.pem --tenant-id  d9abc6fc-fd88-4480-a931-2f7939adbac2  --client-id af7d0998-3108-4a1c-bb52-08707a76b603
→ loaded configuration from /home/manuel/.config/mondoo/mondoo.yml using source $MONDOO_CONFIG_PATH
FTL failed to run query error="rpc error: code = Unknown desc = cannot fetch credentials for microsoft provider: could not parse provided certificate at /home/manuel/Downloads/mondoo-ms365-Dec8.pem: pkcs12: error reading P12 data: asn1: syntax error: sequence truncated"
```

Again same command from shell does work:
![image](https://github.com/mondoohq/cnquery/assets/112621871/9c45cfa7-1949-48f1-8978-5c13a9308f19)
