### ISSUE TITLE
🐛 AWS --discover functionality no longer works for all asset types supported under v8 

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnquery#2623]
**Describe the bug**
cnquery v8 provided functionality to discover and scan a number of different asset types:

```
supported: auto,all,accounts,instances,ssm,ssm-instances,ecr,ecs,resources,ecs-containers-api,ec2-instances-api,ssm-instances-api,ecr-image-api,s3-buckets,cloudtrail-trails,rds-dbinstances,vpcs,security-groups,iam-users,iam-groups,cloudwatch-loggroups,lambda-functions,dynamodb-tables,redshift-clusters,ec2-volumes,ec2-snapshots,efs-filesystems,gateway-restapis,elb-loadbalancers,es-domains,kms-keys,sagemaker-notebookinstances
```

Under cnquery v9, this functionality no longer works. While I have not tested all asset types there are a number of asset types that do not work such as `ec2-instances-api` `ssm`, `ssm-instances-api`, `ecr-image-api`

**Comment by scottford-io** [comment]
@vjeffrey I am adding you to this one. There are a number of AWS variant checks that have filters that will not match until we add these back. 

https://github.com/mondoohq/cnquery/blob/main/providers/aws/resources/discovery.go#L67C31-L70

**Comment by vjeffrey** [comment]
i think these are all covered now, please re-open if not
