### ISSUE TITLE
github.mergeRequest results in `cannot convert primitive with NO type information`

### ISSUE THREAD

**Issue by JosiahOne** [mondoohq/cnquery#2739]
**Describe the bug**
`github.mergeRequest` results in `cannot convert primitive with NO type information` instead of returning valid data as part of a GitHub repository.

**To Reproduce**

1. Get yourself a PAT and export: `GITHUB_TOKEN="<stuff>"`
2. Connect to a repo: `cnquery shell github repo <ORG>/<REPO>`
3. Run the following query: `github.mergeRequest`

We get:

```
cnquery> github.mergeRequest
1 error occurred:
	* cannot convert primitive with NO type information
github.mergeRequest: github.mergeRequest id=null state=null
```

Further, you can crash the provider by running:

```
cnquery> github.mergeRequest { * }
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1b50740]

goroutine 136 [running]:
go.mondoo.com/cnquery/v9/providers/github/resources.(*mqlGithubMergeRequest).reviews(0x1e604c0?)
	/home/runner/_work/cnquery/cnquery/providers/github/resources/github_repo.go:686 +0x60
go.mondoo.com/cnquery/v9/providers/github/resources.(*mqlGithubMergeRequest).GetReviews.func1()
	/home/runner/_work/cnquery/cnquery/providers/github/resources/github.lr.go:4215 +0x8b
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.GetOrCompute[...](0xc000282ad8?, 0xc0002ed7c4)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/runtime.go:240 +0x3a
go.mondoo.com/cnquery/v9/providers/github/resources.(*mqlGithubMergeRequest).GetReviews(0x10076d8?)
	/home/runner/_work/cnquery/cnquery/providers/github/resources/github.lr.go:4204 +0x3f
go.mondoo.com/cnquery/v9/providers/github/resources.glob..func208({0x206f420?, 0xc000282960?})
	/home/runner/_work/cnquery/cnquery/providers/github/resources/github.lr.go:803 +0x30
go.mondoo.com/cnquery/v9/providers/github/resources.GetData({0x206f420, 0xc000282960}, {0xc0004c8488, 0x7}, 0x23?)
	/home/runner/_work/cnquery/cnquery/providers/github/resources/github.lr.go:918 +0x16b
go.mondoo.com/cnquery/v9/providers/github/provider.(*Service).GetData(0x1df1b40?, 0xc00025a620)
	/home/runner/_work/cnquery/cnquery/providers/github/provider/provider.go:248 +0x3ea
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.(*GRPCServer).GetData(0x1e1dde0?, {0xc00025a620?, 0x10c84c6?}, 0x0?)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/grpc.go:121 +0x1e
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin._ProviderPlugin_GetData_Handler({0x1df1b40?, 0xc0003f0820}, {0x20763f0, 0xc0000ab890}, 0xc000213b00, 0x0)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:266 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00044c000, {0x20763f0, 0xc0000aaff0}, {0x207b478, 0xc0004f61a0}, 0xc00045e900, 0xc0000ab9e0, 0x2982cd8, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc00044c000, {0x207b478, 0xc0004f61a0}, 0xc00045e900)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x86
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 42
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x145
1 error occurred:
	* the 'github' provider crashed
github.mergeRequest: {
  repoName: the 'github' provider crashed
  title: the 'github' provider crashed
  assignees: the 'github' provider crashed
  owner: the 'github' provider crashed
  id: the 'github' provider crashed
  state: the 'github' provider crashed
  reviews: the 'github' provider crashed
  createdAt: the 'github' provider crashed
  number: the 'github' provider crashed
  labels: the 'github' provider crashed
  commits: the 'github' provider crashed
}
```

**Expected behavior**
A list of pull requests should be returned.

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS] macOS 
- OS Version: [e.g. 13.0] 14.1.2

```
cnquery version
cnquery 9.9.4 (cb48efb7, 2023-12-01T10:42:03Z)
```

```
cnquery providers list

→ builtin (found 2 providers)

  core 9.1.5
  mock 9.0.0 with connectors: mock

→ /Users/jsbruner/.config/mondoo/providers (found 3 providers)

  aws 9.1.9 with connectors: aws
  github 9.1.9 with connectors: github
  os 9.1.11 with connectors: local, ssh, winrm, vagrant, container, docker, filesystem

→ /Library/Mondoo/providers has no providers
```

**Additional context**

**Comment by vjeffrey** [comment]
it looks like the merge requests field is `openMergeRequests`, and it's at the repo level:

```
cnquery> github.repository.openMergeRequests
github.repository.openMergeRequests: [
  0: github.mergeRequest id=1628891 state="open"
```

i think we need to look at our autocomplete. having that work at all levels of the query would help  a lot with these situations

**Comment by JosiahOne** [comment]
Interesting. But isn't `openMergeRequests` a sort of filter on all merge requests? In this case I need all merge requests in the repository. I don't see a way to find that and https://mondoo.com/docs/mql/resources/github-pack/github.mergeRequest/ seems to imply `github.mergeRequest` *is* a valid field to query.

**Comment by vjeffrey** [comment]
the "open" part is a filter we're sending in to the api when requesting. we can totally add a field for the closed pull requests, or even all. performance may be impacted given the size of the response there, but it's an option - would either of those options be helpful @JosiahOne ?

**Comment by JosiahOne** [comment]
@vjeffrey Totally! The "all" option seems cleanest to me (I could add filters on state if needed) but simply adding `closedMergeRequests` would be adequate.

As for this issue itself, a clearer error message and preventing the crash in the provider is probably all that's needed.

**Comment by mariuskimmina** [comment]
Quick update, you can now use `github.mergeRequest(number: 2183)` to get a single PR via it's number (more efficient than filtering on openMergeRequests because you don't fetch all the open ones first)
This also prevents the provider panic and gives a bit better error message on doing just `github.mergeRequest`.

**Comment by mariuskimmina** [comment]
With the next provider release (probably later today) we add `closedMergeRequests` and `allMergeRequests` to `github.repository`.

Keep in mind that for repos with thousands of PRs this can take a while, also Github has a rate limits to 5000 requests per hour.
