### ISSUE TITLE
Encoding problem with german special char

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnquery#2782]
```coffee
auditpol.entry subcategory="Ticketvorg\x84nge des Kerberos-Diensts" inclusionsetting="No Auditing" exclusionsetting=""
```

I can not search for it like:

```coffee
auditpol.where(subcategory == "Ticketvorgänge des Kerberos-Diensts")
```

**Comment by atomic111** [comment]
this is also not working:

```coffee
auditpol.where(subcategory == "Ticketvorg\x84nge des Kerberos-Diensts")
```

**Comment by chris-rock** [comment]
Most likely powershell returns Windows-1252 encoding and something is wrong with the return values. Probably best is to set the default encoding in powershell to utf8. See https://stackoverflow.com/questions/40098771/changing-powershells-default-output-encoding-to-utf-8
