### ISSUE TITLE
:bug: `aws.elb.classicLoadBalancers` - `attributes` field runs into error

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#2853]
**Describe the bug**

The attributes field in `aws.elb.classicLoadBalancers {attributes}` fails to be populated correctly:

![image](https://github.com/mondoohq/cnquery/assets/112621871/c6828e8a-0774-4387-990e-6055648a74cb)

**To Reproduce**

1. Create a AWS ELB Classic Loadbalancer (easy from console, 1min)
2. Run from `cnspec aws shell` `aws.elb.classicLoadBalancers {attributes}` 
3. 

**Expected behavior**
The field `attributes` should populate correctly. 

**Screenshots or CLI Output**
```
aws.elb.classicLoadBalancers: [
  0: {
    name: "classic-lb-test-44"
    arn: "arn:aws:elasticloadbalancing:us-east-1:286597963329:loadbalancer/classic/classic-lb-test-44"
    createdTime: 2023-12-16 01:04:34.86 +0100 CET
    scheme: "internet-facing"
    listenerDescriptions: [
      0: {
        Listener: {
          InstancePort: 80.000000
          InstanceProtocol: "HTTP"
          LoadBalancerPort: 80.000000
          Protocol: "HTTP"
          SSLCertificateId: null
        }
        PolicyNames: []
      }
    ]
    vpcId: "vpc-00c176a672b21ec7c"
    dnsName: "classic-lb-test-44-1176479729.us-east-1.elb.amazonaws.com"
    attributes: operation error Elastic Load Balancing v2: DescribeLoadBalancerAttributes, https response error StatusCode: 400, RequestID: a4a9cd4d-2181-4d1f-8c11-97c7c983dbe5, api error ValidationError: 'arn:aws:elasticloadbalancing:us-east-1:286597963329:loadbalancer/classic/classic-lb-test-44' is not a valid loadbalancer ARN
  }
]
```
**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**

**Comment by tas50** [comment]
There's a few problems in the code right now. First off, we're generating ARNs for classic ELBs incorrectly by including Classic in the value. With that corrected we get the real error, which is the elasticloadbalancerv2 package does not allow querying attributes on the classic load balancers. We need to change back to the v1 API there to access classic load balancer attributes.
