### ISSUE TITLE
 OS Resource `group` throws Error: `cannot convert primitive with NO type information`

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#2937]
## Describe the bug
In `cnspec v.8.24.8` this still works:

```
cnspec> group("140") {*}
group: {
  name: "docker"
  members: [
  0: user name="manuel" uid=1000 gid=1000
  ]
  gid: 140
  sid: ""
}
```

In `cnspec v9.12.1 (fec2782, unknown)` it doesn't:

## To Reproduce

1. With `cnspec v9.12.1 `
2. Run:
```
cnspec> group("140") {*}
rpc error: code = Unknown desc = [os] cannot set 'id' in resource 'group', field not found
group: no data available

```

## Expected behavior
Ideally it would be possible to supply `gid`, `name` or `sid` on windows to `group`.
Example:

```
cnspec> group(name: "Cert Publishersa") {*}
1 error occurred:
        * cannot convert primitive with NO type information
group: {
  sid: "S-1-5-21-2877263174-666010912-2204378277-517"
  gid: -1
  members: []
  name: "Cert Publishersa"
}
```

### Linux
![image](https://github.com/mondoohq/cnquery/assets/112621871/db2b5337-d686-4631-bdf3-3f0c311bf63b)

### Windows
![image](https://github.com/mondoohq/cnquery/assets/112621871/8f73bfde-8e81-4edc-9d6d-159af440caf0)

![image](https://github.com/mondoohq/cnquery/assets/112621871/125df628-abeb-4d04-8e7a-c56b0e23459a)

![image](https://github.com/mondoohq/cnquery/assets/112621871/0a2c2fed-b350-4dca-adbd-e06d11923eb7)

**Desktop (please complete the following information):**

- `Ubuntu 22.04.3 LTS`

```
  ]
  kind: "baremetal"
  build: "2159"
  version: "20348"
  title: "Microsoft Windows Server 2022 Datacenter"
  arch: "64-bit"
```

**Additional context**

**Comment by vjeffrey** [comment]
looks like we're missing an init for group

**Comment by arlimus** [comment]
Thank you for outlining this, the behavior pre v9 was actually inconsistent.

For example:
- in v8+v9 you can init a user via `user(uid: 123)` but not a group
- in v8 you can init a group via `group("123")` but not a user

We will align to the post-v8 world by supporting the mode outlines by user
