### ISSUE TITLE
Add support for .all with maps

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnquery#2951]
**Describe the bug**
When checking values for maps the output is not actionable:

### EX. AWS EBS ENCRYPTION
The data query for EBS encryption in AWS:

```
cnspec> aws.ec2.ebsEncryptionByDefault
aws.ec2.ebsEncryptionByDefault: {
  ap-northeast-1: false
  ap-northeast-2: false
  ap-northeast-3: false
  ap-south-1: false
  ap-southeast-1: false
  ap-southeast-2: false
  ca-central-1: false
  eu-central-1: false
  eu-north-1: false
  eu-west-1: false
  eu-west-2: false
  eu-west-3: false
  sa-east-1: false
  us-east-1: false
  us-east-2: false
  us-west-1: false
  us-west-2: false
}
```

The current cnspec check and output is as follows:

```
cnspec> aws.ec2.ebsEncryptionByDefault.values.all(_ == true)
[failed] [].all()
  actual:   [
    0: bool false
    1: bool false
    2: bool false
    3: bool false
    4: bool false
    5: bool false
    6: bool false
    7: bool false
    8: bool false
    9: bool false
    10: bool false
    11: bool false
    12: bool false
    13: bool false
    14: bool false
    15: bool false
    16: bool false
  ]
  ```

The output above is not actionable because it does not show which regions need to be remediated. 

**Expected behavior**
```
aws.ec2.ebsEncryptionByDefault.all( values == true )
```

```
[failed] [].all()
  actual:   [
    ap-northeast-1: false
    ap-northeast-2: false
    ap-northeast-3: false
    ap-south-1: false
    ap-southeast-1: false
    ap-southeast-2: false
   ...
]
```

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**

**Comment by arlimus** [comment]
Closed in https://github.com/mondoohq/cnquery/pull/2954
