### ISSUE TITLE
:bug: `ports.` resource error `cannot access stat for /proc/net/tcp6` when IPv6 disabled

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#2957]
**Describe the bug**
`ports.` resource errors `cannot access stat for /proc/net/tcp6` when IPv6 disabled via kernel boot arguments.

**To Reproduce**

On RHEL 9:

1. Run the following commands as `root`

```
grubby --update-kernel ALL --args 'ipv6.disable=1'
grub2-mkconfig -o /boot/grub2/grub.cfg
reboot
```

2. No when accessing the `ports.` resource via

```
ports
```

The following error occurs:

![image](https://github.com/mondoohq/cnquery/assets/112621871/cca7c1c4-6320-4d8a-805a-e5978681eab9)

**Expected behavior**
The `ports` resource needs to work regardless of IPv6 being disabled via Kernel Boot parameters, because most CIS Hardening Guides recommend IPv6 to be disabled.

**Desktop (please complete the following information):**

```
cnspec 9.13.0 (ea1ed4d, 2024-01-03T20:54:04Z)

[root@ip-10-0-101-162 ~]# cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.3 (Blue Onyx)"

[root@ip-10-0-101-162 ~]# uname -a
Linux ip-10-0-101-162.ec2.internal 5.14.0-362.8.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 8 17:36:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

**Additional context**

**Comment by schnipschnap** [comment]
@vjeffrey Can we treat this with a higher priority? Would be good to fix this for lecos
