### ISSUE TITLE
`aws.efs.filesystem` -> ERROR - cannot convert primitive with NO type information 

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#3036]
![image](https://github.com/mondoohq/cnquery/assets/112621871/3985a675-c792-4573-af21-f76b60166dd3)
## Description

`aws.efs.filesystems` works fine , whereas `aws.efs.filesystem` fails to return that data.

```
cnspec> aws.efs.filesystem
1 error occurred:
	* cannot convert primitive with NO type information
aws.efs.filesystem: aws.efs.filesystem name=null id=null region=null

```

**Expected behavior**

**Screenshots or CLI Output**

**Desktop (please complete the following information):**
```
cnspec v9.14.0 (1f8621d, unknown
```

**Additional context**

**Comment by vjeffrey** [comment]
`aws.efs.filesystem`

@mm-weber were you using fine grained scanning for this /on a efs filesystem asset?

**Comment by mm-weber** [comment]
Hi @vjeffrey,

just tried this on `cnspec v10.2.0 (3cc095e, unknown)`:
![image](https://github.com/mondoohq/cnquery/assets/112621871/35d0e725-256c-483b-8459-27b0339d2d8b)

**Comment by mm-weber** [comment]
This works now:

![image](https://github.com/mondoohq/cnquery/assets/112621871/c49693d9-9bca-4a19-b30d-2c9f2b08348f)
