### ISSUE TITLE
Context time to short for installing plugins

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnquery#3107]
**Describe the bug**

```
53.05 → installing provider 'ms365' version=10.0.0
83.05 FTL could not initialize providers error="failed to install ms365-10.0.0: context deadline exceeded (Client.Timeout or context cancellation while reading body)
```

**To Reproduce**

Some internet connections are slower and we need to make the download behavior more resilient.

**Expected behavior**

Do 3 retries before we fail.

**Comment by imilchev** [comment]
isn't this fixed now with the retries? I will close it. If this is a different issue, please re-open
