### ISSUE TITLE
CLI should output a helpful warning when not specifying a asset

### ISSUE THREAD

**Issue by benr** [mondoohq/cnquery#317]
When executing the shell with no additional arguments the error is cryptic to the new user, we should catch this scenario and print a message like "No Asset Specified; did you mean 'cnquery shell local'?"

Here's how it looks today: 

```
$ cnquery shell
→ loaded configuration from xxxxxxxxxxxx using source $MONDOO_CONFIG_PATH
→ discover related assets for 0 asset(s)
→ resolved assets resolved-assets=0
FTL could not find an asset that we can connect to
```

**Comment by tas50** [comment]
Same issue on cnspec: https://github.com/mondoohq/cnspec/issues/95

**Comment by chris-rock** [comment]
fixed via https://github.com/mondoohq/cnquery/pull/344
