### ISSUE TITLE
Cannot use kubelet resource on RKE clusters

### ISSUE THREAD

**Issue by imilchev** [mondoohq/cnquery#330]
I have an RKE cluster and controls that validate the kubelet config are failing with the following error:
```
failed to create resource 'k8s.kubelet': error when getting file content: open /mnt/host/var/lib/kubelet/config.yaml: no such file or directory; failed to create resource 'k8s.kubelet': error when getting file content: open /mnt/host/var/lib/kubelet/config.yaml: no such file or directory
```

**Comment by imilchev** [comment]
I believe there should be no error if the file doesn't exist. It is not a mandatory file in the first place

**Comment by czunker** [comment]
Strange, we had the issue also on AKS, and I thought I fixed it: https://github.com/mondoohq/cnquery/pull/246

Could you please try to verify this with the latest cnquery binary?

**Comment by imilchev** [comment]
Indeed, with v7 it works. I will close this issue
