### ISSUE TITLE
Feature request: GKE  `.networkPolicy'` field.

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#3868]
Is it possible to add the following field to `gcp.project.gke.cluster.` ?

`gcloud  container clusters describe <cluster-name> --zone us-central1 --format json | jq '.networkPolicy'`

```
{
"enabled": true
}
```

**Comment by tas50** [comment]
Fixed in https://github.com/mondoohq/cnquery/pull/3873

**Comment by tas50** [comment]
@mm-weber Feel free to open this one up if the latest provider isn't meeting the need

**Comment by mm-weber** [comment]
There's an issue with the `.networkPolicy` (sub-)properties:

```
cnspec> gcp.project.gke.cluster.networkPolicyConfig
failed to convert dict to primitive, unsupported child type: containerpb.NetworkPolicy_Provider
```
![image](https://github.com/mondoohq/cnquery/assets/112621871/729dd797-316e-4f6f-98f2-8c4527848078)


To re-produce, use deploy a cluster on GKE.

1) First enable `Calico Kubernetes Network policy` on the control plane (takes awhile).
2) Then enable `Calico Kubernetes Network policy` on `Enable Calico Kubernetes network policy for nodes`
![image](https://github.com/mondoohq/cnquery/assets/112621871/239c3da5-6dc5-4d2c-a1f5-3c0c6c5ccf74)
