### ISSUE TITLE
docker resource fails with Docker Desktop for macOS

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#424]
**Describe the bug**
When trying to run `docker.containers` on macOS you get an error that cnquery could not connect to the Docker daemon which is running.

**To Reproduce**
1. Start docker desktop mac app
2. Run cnquery shell
3. Run `docker.containers`

**Expected behavior**
Successfully queries docker

**Screenshots**
```
cnquery> docker.containers
Query encountered errors:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
docker.containers: []
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 13

**Comment by imilchev** [comment]
This works for me. @tas50 can you try and re-produce this? If it's not happening on your end too, then we can close the issue

**Comment by tas50** [comment]
I can no longer reproduce this
