### ISSUE TITLE
Need resource `googleworkspace.drive` 

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#4280]
We need a resource `googleworkspace.drive` 

that gives access to `googleworkspace.drive.about` via the v2 API: https://pkg.go.dev/google.golang.org/api/drive/v2,

so we can access the field `domainSharingPolicy` (which can't be accessend in v3)

`googleworkspace.drive.about {domainSharingPolicy}` 

![image](https://github.com/mondoohq/cnquery/assets/112621871/6079756b-38d7-499a-af59-e4e427d9bd6f)

more info here:
https://developers.google.com/drive/api/reference/rest/v2/about

#####

Also needs the field `canCreateDrives`

![image](https://github.com/mondoohq/cnquery/assets/112621871/228ee76f-4066-4d0d-af9e-ee27954cf66d)

**Comment by vjeffrey** [comment]
can get the information thru the resource extension, no way to get this specific one
