### ISSUE TITLE
Add fields in aws.ec2.securityGroups ipPermissions and ipPermissionsEgress for UserIdGroupPairs and PrefixListIds

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnquery#4322]
**Is your feature request related to a problem? Please describe.**

The `aws.ec2.securityGroups` resource is missing two fields that are required to properly assess the security configuration of AWS Security Groups:

- **[PrefixListIds](https://docs.aws.amazon.com/vpc/latest/userguide/managed-prefix-lists.html)** - A managed prefix list is a set of one or more CIDR blocks. You can use prefix lists to make it easier to configure and maintain your security groups and route tables. You can create a prefix list from the IP addresses that you frequently use, and reference them as a set in security group rules and routes instead of referencing them individually. For example, you can consolidate security group rules with different CIDR blocks but the same port and protocol into a single rule that uses a prefix list. If you scale your network and need to allow traffic from another CIDR block, you can update the relevant prefix list and all security groups that use the prefix list are updated. You can also use managed prefix lists with other AWS accounts using Resource Access Manager (RAM).
- **[UserIdGroupPairs](https://docs.aws.amazon.com/vpc/latest/userguide/security-group-rules.html#security-group-referencing)** - When you specify a security group as the source or destination for a rule, the rule affects all instances that are associated with the security groups. The instances can communicate in the specified direction, using the private IP addresses of the instances, over the specified protocol and port.

**Example**

The default security group allows unrestricted traffic from itself, but MQL does not supply that data. 

```json
        {
            "Description": "default VPC security group",
            "GroupName": "default",
            "IpPermissions": [
                {
                    "IpProtocol": "-1",
                    "IpRanges": [],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "UserIdGroupPairs": [
                        {
                            "GroupId": "sg-0de78481fe820f1ac",
                            "UserId": "339712786066"
                        }
                    ]
                }
            ],
            "OwnerId": "339712786066",
            "GroupId": "sg-0de78481fe820f1ac",
            "IpPermissionsEgress": [
                {
                    "IpProtocol": "-1",
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "UserIdGroupPairs": []
                }
            ],
            "VpcId": "vpc-0a12059bfc9086ae0"
        }
```

**MQL**

```
cnspec> aws.ec2.securityGroups.where( region == "us-west-2" && description == /^default/ ) { description ipPermissions {*} ipPermissionsEgress {*}}
aws.ec2.securityGroups.where: [
  0: {
    description: "default VPC security group"
    ipPermissions: [
      0: {
        ipv6Ranges: []
        fromPort: -1
        ipProtocol: "-1"
        id: "sg-0de78481fe820f1ac-0"
        ipRanges: []
        toPort: -1
      }
    ]
    ipPermissionsEgress: [
      0: {
        toPort: -1
        fromPort: -1
        ipProtocol: "-1"
        ipRanges: [
          0: "0.0.0.0/0"
        ]
        id: "sg-0de78481fe820f1ac-0-egress"
        ipv6Ranges: []
      }
    ]
  }
]
```

**Comment by arlimus** [comment]
Classified as p1, because it blocks the check from behaving correctly. Not a p0 because the check works in all cases without internal networks assigned, but it fails in those cases with internal networks.
