### ISSUE TITLE
Error using `googleworkspace.calendars` resource

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#4433]
**Describe the bug**
![image](https://github.com/user-attachments/assets/b1d714bf-faa1-45a3-998a-5be14fe1884c)

**To Reproduce**
`googleworkspace.calendars`

**Comment by preslavgerchev** [comment]
@mm-weber, this sounds like a permission issue and not a cnquery issue. Can you double check if your permissions have the calendars scope (i dont know exactly what that might be)? It should work in that case

**Comment by mm-weber** [comment]
Thanks @preslavgerchev ! 
Was were missing a few OAuth scopes.
