### ISSUE TITLE
`"audit.cve" failed: no value provided for static field "mrn"` error not clear

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#446]
**Describe the bug**
Running `audit.cve` in the shell results in `failed to create resource 'audit.cve': "audit.cve" failed: no value provided for static field "mrn"` which does not give the user enough information to correct their query.

**To Reproduce**
1. cnquery shell
2. audit.cve
3. See error

**Expected behavior**
A clear message that allows the user to take action and correct their queries.

**Comment by chris-rock** [comment]
That resource is not designed for direct invocation yet.

**Comment by tas50** [comment]
Can't reproduce this anymore
