### ISSUE TITLE
Restart provider runtime if required when we start scanning a new asset

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnquery#4589]
**Describe the bug**

You scan 100 assets of the same type. At 51 the provider crashes for any reason. Then all following assets using the same provider also return errors since the provider runtime is not restarted.

**To Reproduce**

Scan multiple assets of same type eg. with asset inventory. Force a panic during the first scan eg. by returning a panic when a resource is called. All following assets return as error.

Related to missing check here https://github.com/mondoohq/cnquery/blob/936494502e4580f008bd524420b064a27216e36a/providers/runtime.go#L207-L211

**Expected behavior**

Within a scan we do not recover the runtime. We only check for a dead runtime when we start scanning a new asset. If the runtime is dead, we restart the provider. Otherwise we keep the existing runtime as we do right now.

**Comment by vjeffrey** [comment]
https://github.com/mondoohq/cnquery/pull/4591
