### ISSUE TITLE
Linux: os.packages resource doesn't return any data on SUSE 15 OS

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#4714]
Tested on SuSE15

`packages` just returns a list containing the mondoo packages on that system:
```
packages.list: [
  0: package name="cnquery" version="11.24.0-1"
  1: package name="cnspec" version="11.24.0-1"
  2: package name="mondoo" version="11.24.0-1"
]
```

It still works on Debian-type OS.

![image](https://github.com/user-attachments/assets/6e9e0591-8e4d-475b-83b4-1f774796263b)

**Comment by mm-weber** [comment]
```
# cnquery version
cnquery 11.24.0 (69fa7d1e0b1, 2024-10-01T09:31:56Z)
```

**Comment by VasilSirakov** [comment]
Documenting this here as well. The issue is caused by the vendor name of SuSE changing from `SUSE LLC` to `SUSE LLC <https://www.suse.com/>`.

Will get to fixing this after I align with Chris on what we want to display as a vendor name.
