### ISSUE TITLE
Enforce device name in device connection

### ISSUE THREAD

**Issue by preslavgerchev** [mondoohq/cnquery#4729]
We currently don't enforce that the device name is specified in the device connection, which means that if not provided we do a best-effort search. We should enforce that either of these 3 is passed in to identifty the device:
 * device name
 * LUN (used on Azure LinuxVMs)
 * serial number (used on Azure Windows VMs)

Any of these 3 opts should suffice to identify an unique device that we can then scan.

We don't enforce the device name currently primarily because of AWS blocks (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html) as AWS gives no guarantees that a device, mounted under `/dev/sda` will end up under `/dev/sda` on the actual VM. However, it seems that the last char is usually the same (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html). We should add logic to support that.

**Comment by slntopp** [comment]
Correction, it's last two chars, e.g. /dev/s[xx] -> /dev/xv[xx]

From [docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html):
> Depending on the block device driver of the kernel, the device could be attached with a different name than you specified. For example, if you specify a device name of /dev/sdh, your device could be renamed /dev/xvdh or /dev/hdh. In most cases, the trailing letter remains the same. In some versions of Red Hat Enterprise Linux (and its variants, such as CentOS), the trailing letter could change (/dev/sda could become /dev/xvde). In these cases, the trailing letter of each device name is incremented the same number of times. For example, if /dev/sdb is renamed /dev/xvdf, then /dev/sdc is renamed /dev/xvdg. Amazon Linux creates a symbolic link for the name you specified to the renamed device. Other operating systems could behave differently.

**Comment by preslavgerchev** [comment]
Thi is now fully enforced, closing
