### ISSUE TITLE
k8s resources include resourceversion label twice

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#647]
**Describe the bug**
A k8s resource has the resource version attached twice as label. But it has has two different spellings.

**To Reproduce**
1. Scan k8s resource
2. Check Web UI
3. See label twice

**Expected behavior**
Label should only be saved once.

**Screenshots or CLI Output**
![image](https://user-images.githubusercontent.com/827818/208506893-5ff6f960-83de-46e9-a65f-3a313926032c.png)

**Comment by imilchev** [comment]
So something is adding the label `k8s.mondoo.com/resource-version` and `k8s.mondoo.com/resourceversion`
