### ISSUE TITLE
CLI flag option docs changing order each time they're generated

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#680]
**Describe the bug**
Many of our CLI flags take a number of different arguments (think output). When the documentation is generated we include all the options, but the list of options is coming back in a different order each time. This is causing the files in the repo to change each time for new reason.

Example generated content

```
  -o, --output string                    Set output format: report, yaml, junit, compact, summary, full, csv, json (default "compact")
```

**To Reproduce**
1. Go to cnquery repo
2. Run `go run apps/gen-docs/main.go --docs-path ../docs/docs/cnquery/cli/.`
3. Check docs content
4. Run `go run apps/gen-docs/main.go --docs-path ../docs/docs/cnquery/cli/.` again
5. Check docs content and note the order of options changed

**Expected behavior**
The options should just get alphabetically sorted

**Comment by jaym** [comment]
i cant reproduce this in cnquery. I can see this happening for cnspec
