### ISSUE TITLE
ORing two false queries giving true result

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/cnquery#683]
**Describe the bug**
Given two independent false queries:
k8s.ingress.tls.length == 0
k8s.ingress.tls{ certificates { expiresIn.days < 15 } }

When they are ORed into a single query, a true result is returned

**To Reproduce**
1. Create a minikube cluster with `minikube start --addons=ingress` 
2. Once the cluster is up, create an Ingress resource. Just use the existing example data in ./motor/providers/k8s/resources/testdata/ingress.yaml (just remove two of the Ingress resources from the YAML named no-tls-ingress and ingress-to-non-existent-secret)
3. kubectl apply -f ./motor/providers/k8s/resources/testdata/ingress.yaml # after removing those two extra Ingress resources
4. Show that the number of TLS entries in the resource is actually `not == 0`
`cnspec run k8s --discover ingresses --namespaces default -c "k8s.ingress.tls.length == 0"`
5. Show that the certificates do not expire in less than 10 days
`cnspec run k8s --discover ingresses --namespaces default -c "k8s.ingress.tls{ certificates { expiresIn.days < 10 }}"
6. Now combine both false statements into one big ORed statement
`cnspec run k8s --discover ingresses --namespaces default -c "k8s.ingress.tls.length == 0 || k8s.ingress.tls{ certificates { expiresIn.days < 10 }}"`
7. See the `true` result

**Expected behavior**
ORing two false queries should not produce a true.

**Screenshots or CLI Output**

```
[jdiaz@fedora cnquery (main *$%=)]$ ./cnquery run k8s --discover ingresses --namespaces default -c "k8s.ingress.tls.length == 0"
→ discover related assets for 1 asset(s)
→ use cluster name from kube config cluster-name=minikube
→ resolved assets resolved-assets=1
[failed] k8s.ingress.tls.length == 0
  expected: == 0
  actual:   1

[jdiaz@fedora cnquery (main *$%=)]$ ./cnquery run k8s --discover ingresses --namespaces default -c "k8s.ingress.tls{ certificates { expiresIn.days < 10 }}"
→ discover related assets for 1 asset(s)
→ use cluster name from kube config cluster-name=minikube
→ resolved assets resolved-assets=1
k8s.ingress.tls: [
  0: {
    certificates: [
      0: {
        expiresIn.days < 10: false
      }
    ]
  }
]
[jdiaz@fedora cnquery (main *$%=)]$ ./cnquery run k8s --discover ingresses --namespaces default -c "k8s.ingress.tls.length == 0 || k8s.ingress.tls{ certificates { expiresIn.days < 10 }}"
→ discover related assets for 1 asset(s)
→ use cluster name from kube config cluster-name=minikube
→ resolved assets resolved-assets=1
[ok] true
```

**Desktop (please complete the following information):**
- OS: linux
- OS Version: Fedora 37
- Browser if applicable n/a
- Browser Version: n/a

**Additional context**

**Comment by joelddiaz** [comment]
A much simpler reproducer:

Start up minikube `minikube start`.

Run first query that should be false:
`cnquery run k8s --discover pods --namespaces kube-system -c "k8s.pod.containers.length == 0"`

Second false query:
`cnquery run k8s --discover pods --namespaces kube-system -c "k8s.pod.containers { name == 'doNotMatchThis' }"`

Now combine both with OR and see `[ok] true` as the result:
`cnquery run k8s --discover pods --namespaces kube-system -c "k8s.pod.containers.length == 0 || k8s.pod.containers { name == 'doNotMatchThis'}"`

**Comment by joelddiaz** [comment]
After discussion with @jaym , it turns out that the handling of a list full of `false` is still a truthy thing.

So perhaps a more appropriate MQL statement would look like:
`k8s.pod.containers.length == 0 || k8s.pod.containers.all ( name == 'doNotMatchThis' )`

^^^ That indeed does get the desired results/behavior.

We can close this issue out assuming that a list full of false, or even an empty list being handles as `true` is desired/intended behavior. I certainly understand the rationale for why it is handled that way, but can also see why it would be surprising to someone unfamiliar with these subtleties.

**Comment by chris-rock** [comment]
Thank you for clarifying this @joelddiaz. I am going to close this. Please re-open if you think this is still an issue
