### ISSUE TITLE
Slack, Okta, and Google Workspace missing in readme

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#975]
**Describe the bug**
Slack, Okta, and Google Workspace need to be in the readme with connection examples.

**Comment by misterpantz** [comment]
@benr will take care of this in both cnquery and cnspec... because he's a 🌟!

**Comment by tas50** [comment]
@misterpantz cnquery is done

**Comment by misterpantz** [comment]
Oh look! @preslavgerchev already did it! Yay!

**Comment by misterpantz** [comment]
https://github.com/mondoohq/cnspec/pull/385 updates cnspec.
